<script lang="ts">
  import type { PageData } from './$types';

  export let data: PageData;

  // Helper function to format date (can move to a shared utils file later)
  function formatDate(dateString: string) {
    try {
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    } catch (e) {
      console.error("Error formatting date:", dateString, e);
      return dateString;
    }
  }
</script>

<article class="container blog-post">
  <h1>{data.post.title}</h1>
  <p class="post-meta">
    Published on {formatDate(data.post.date)}
    {#if data.post.tags && data.post.tags.length > 0}
      <span class="tag-separator">|</span> Tags:
      <span class="tag-container">
        {#each data.post.tags as tag}
          <span class="tag">{tag}</span>
        {/each}
      </span>
    {/if}
  </p>

  <div class="post-content">
    <!-- Render the HTML content generated by marked -->
    {@html data.post.content}
  </div>

</article>

<style>
  .container.blog-post {
    max-width: 900px; /* Consistent width */
    margin: 2rem auto;
    padding: 0 1.5rem;
    font-family: 'Georgia', serif;
    line-height: 1.7;
  }

  h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
    line-height: 1.2;
    font-weight: bold;
    color: #222;
  }

  .post-meta {
    font-size: 0.9rem;
    color: #666;
    margin-bottom: 2.5rem;
    font-family: sans-serif;
    border-bottom: 1px solid #eee;
    padding-bottom: 1rem;
  }

  .tag-separator {
      margin: 0 0.5em;
  }

  .tag-container {
    display: inline-flex;
    flex-wrap: wrap;
    gap: 0.4rem;
    margin-left: 0.3rem;
    vertical-align: middle;
  }

  .tag {
    background-color: #f0f0f0;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    color: #555;
    white-space: nowrap;
  }

  .post-content {
    font-size: 1.1rem;
    color: #333;
  }

  /* Basic styling for potential HTML elements rendered from markdown */
  .post-content :global(h2) {
      font-size: 1.8rem;
      margin-top: 2.5rem;
      margin-bottom: 1rem;
      border-bottom: 1px solid #eee;
      padding-bottom: 0.4rem;
  }

  .post-content :global(h3) {
      font-size: 1.4rem;
      margin-top: 2rem;
      margin-bottom: 0.8rem;
  }

  .post-content :global(p) {
      margin-bottom: 1.2rem;
  }

  .post-content :global(ul),
  .post-content :global(ol) {
      padding-left: 2rem;
      margin-bottom: 1.2rem;
  }

  .post-content :global(li) {
      margin-bottom: 0.5rem;
  }

  .post-content :global(blockquote) {
      margin-left: 1rem;
      padding-left: 1rem;
      border-left: 3px solid #eee;
      color: #666;
      font-style: italic;
  }

  .post-content :global(pre) {
      background-color: #f8f8f8;
      padding: 1rem;
      border-radius: 4px;
      overflow-x: auto; /* Handle code horizontal scroll */
      font-family: monospace;
      font-size: 0.9rem;
  }

  .post-content :global(code) {
      font-family: monospace;
      font-size: 0.9em; /* Slightly smaller for inline code */
      background-color: #f0f0f0;
      padding: 0.1em 0.3em;
      border-radius: 3px;
  }

    .post-content :global(pre code) {
        background-color: transparent;
        padding: 0;
        font-size: inherit; /* Code inside pre should inherit pre's size */
    }

  .post-content :global(a) {
      color: #007bff;
      text-decoration: none;
  }
  .post-content :global(a:hover) {
      text-decoration: underline;
  }

  /* Styles for the temporary <pre> block showing raw markdown */
  /* Remove or comment out the specific styles for the <pre> tag now */
  /*
  pre {
    white-space: pre-wrap; 
    word-break: break-word;
    background-color: #eee;
    padding: 1rem;
    border-radius: 4px;
    font-family: monospace;
    font-size: 0.9rem;
  }
  */

</style> 